fun main() {
    val a: Int = 123
//    a = 444 // 에러가 발생함.
}